---
doctrine:
    dbal:
        driver: pdo_mysql
        dbname: '%env(DATABASE_NAME)%'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        server_version: 8.0
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain:
                type: xml
                prefix: 'App\Domain\Model'
                dir: '%kernel.project_dir%/src/Infrastructure/Database/ORM/Mapping'
                is_bundle: false
